version: '3.7'

services:
  db-dev:
    container_name: db-dev
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_vol_dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DEV_DB_NAME}
      - MYSQL_USER=${DEV_DB_USER}
      - MYSQL_PASSWORD=${DEV_DB_PASSWORD}
    ports:
      - 3306:3306

  api-dev:
    container_name: api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DEV_DB_HOST=db-dev
      - CI_DB_HOST=db-dev
    volumes:
      - '.:/usr/src/app:rw'
    command: npm run start:dev
    links:
      - 'db-dev'
    env_file:
      - ./.env
    ports:
      - ${PORT}:8080

volumes:
  db_vol_dev:
